name: Branch name

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: branch
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
