name: Branch name

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: branch
        run: |
          echo ${{ github.head_ref }}
          echo '${{ toJSON(github) }}
